config/routes.rb
Rails.application.routes.draw do
  root 'application#welcome'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/home', to: 'users#home'

  get 'auth/:provider/callback', to: 'sessions#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users do
    resources :remedies
  end

  resources :herbs
  resources :remedies
  


  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/herb.rb
class Herb < ApplicationRecord
  has_many :remedy_herbs
  has_many :remedies, through: :remedy_herbs
  validates :name, :latin_name, :family, :medicinal_parts, :taste, :energetics, :action, :ideal_for, :application, :dosage, :considerations, presence: true
  validates :name, :latin_name, uniqueness: true
  scope :search, -> {where("name || taste || energetics || action || ideal_for LIKE ?", "%#{search}")}

def self.search(search)
    where("name || taste || energetics || action || ideal_for LIKE ?", "%#{search}%")
  end
end

app/models/remedy.rb
class Remedy < ApplicationRecord
    belongs_to :user
    has_many :remedy_herbs, dependent: :destroy
    has_many :herbs, through: :remedy_herbs
    validates :title, :directions, presence: true
    validates :title, uniqueness: true
    accepts_nested_attributes_for :remedy_herbs
    scope :search, -> {where("title LIKE ?", "%#{search}%")}

    # def self.herb
    #     self.remedy_herbs.each do |h|
    #         h.herb.name = herbs
    #     end
    # end



    def self.search(search)
        where("title LIKE ?", "%#{search}%")

      end
end

# e.g. "mint"
# find all of the remedies that have mint in their remedy herbs array
# finding the herb in the herb class, taking its id and matching to the id in the array of remedy herbs of whatever remedy it exists in

app/models/remedy_herb.rb
class RemedyHerb < ApplicationRecord
    belongs_to :herb
    belongs_to :remedy, optional: true
    validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :remedies
    has_secure_password
    validates :name, :email, :password, presence: true
    validates :email, uniqueness: true
    accepts_nested_attributes_for :remedies


    def self.find_or_create_by_omniauth(auth_hash)
        self.where(uid: auth_hash["uid"]).first_or_create do |user|
            user.name = auth_hash[:info][:name]
            if auth_hash[:info][:email]
                user.email
            else
                user.email = SecureRandom.hex
            end
            
            user.password = SecureRandom.hex
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    

    def home
    end

    private

    
      def logged_in?
        current_user != nil
      end
    
      def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      end
    
      def require_login
        redirect_to "/" unless session.include? :user_id
      end

      def user_logged_in
        if !logged_in?
          redirect_to root_path
        end
      end
      helper_method :current_user, :user_logged_in
end

app/controllers/herbs_controller.rb
class HerbsController < ApplicationController

    def index
        @herbs = Herb.all.order('name ASC')
        if params[:search] && params[:search].length >= 3
            @herbs = Herb.search(params[:search]).order('name ASC')
        elsif params[:search] && params[:search].length < 3
            flash.now[:search_error] = "Search must be more than 3 characters"
            @herbs = Herb.all.order('name ASC')
        else
        @herbs = Herb.all.order('name ASC')
        end  
        render 'index'
    end
    
    def new
        @herb = Herb.new
    end

    def create
         @herb = Herb.new(herb_params)
         if @herb.save
           redirect_to herb_path(@herb)
        else
            flash[:herb_not_created] = "Please make sure all fields are filled in"
            render :new
        end
    end

    def show
        @herb = Herb.find_by_id(params[:id])
    end

    def edit
        @herb = Herb.find_by_id(params[:id])
    end

    def update
        @herb = Herb.find_by_id(params[:id])
        if @herb.update(herb_params)
           redirect_to herbs_path
        else
            flash[:herb_not_edited] = "please make sure no fields are left blank"
            render "edit"
        end
    end

    def destroy
        @herb = Herb.find_by_id(params[:id])
        @herb.destroy
        redirect_to herbs_path
    end

    private

    def herb_params
        params.require(:herb).permit(
            :name,
            :latin_name,
            :family,
            :medicinal_parts,
            :taste,
            :energetics,
            :action,
            :ideal_for,
            :application,
            :dosage,
            :considerations
        )
    end
end

app/controllers/remedies_controller.rb
class RemediesController < ApplicationController
  before_action :user_logged_in

  def index
    @remedies = current_user.remedies
    @remedies = current_user.remedies.search(params[:search])
    binding.pry
    
  end

  def show
    @remedy = Remedy.find_by_id(params[:id])
  end

  def new
    @user = User.find_by_id(session[:user_id])
    @remedy = Remedy.new(user_id: session[:user_id])
    4.times { @remedy.remedy_herbs.build }
  end

  def create
    @user = User.find_by_id(remedy_params[:user_id])
    @remedy = current_user.remedies.create(remedy_params)
    @remedy.user = @user
      if @remedy.persisted?
        @remedy_herb = RemedyHerb.create(remedy_id: remedy.id, herb_id: remedy_params[:remedy_herbs_attributes][:herb_id], quantity: remedy_params[:remedy_herbs_attributes][:quantity])
        redirect_to user_remedies_path
      else
        flash[:empty_field] = "Remedy name and directions can not be blank"
        render :new
      end
  end

  def edit
    @user = User.find_by_id(params[:user_id])
    @remedy = Remedy.find_by_id(params[:id])
  end

  def update
    @remedy = Remedy.find_by_id(params[:id])
    if @remedy.update(remedy_params)
      redirect_to user_remedy_path(@remedy.user)
    else
      flash[:empty_edit] = "Remedy name and or directions can not be blank"
      render "edit"
    end 
  end

  def destroy
    @remedy = Remedy.find_by_id(params[:id])
    @remedy.destroy
    flash[:notice] = "Successfully destroyed remedy."
    redirect_to home_path
  end

  private

  def remedy_params
    params.require(:remedy).permit(:title, :directions, :search, :user_id, remedy_herbs_attributes: [
      :id,
      :quantity,
      :herb_id,
      :remedy_id,
    ])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if auth_hash = request.env["omniauth.auth"]
        user = User.find_or_create_by_omniauth(auth_hash)
        session[:user_id] = user.id
        redirect_to controller: "users", action: "home"
    else
      @user = User.find_by(email: params[:user][:email])
      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to home_path
      else
        flash[:alert] = "Email or Password did not match"
        render :new
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end 

    def create
        @user = User.create(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to controller: 'users', action: 'home'
        else
            render 'new'
        end
     end

     def home
    
     end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/herbs_helper.rb
module HerbsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/welcome.html.erb
<div class="container">
  <div class="col-md-8 col-md-offset-2">
  <br>
    <h1>Welcome to Your Herb Garden!!</h1>
    <br>

    <h3>Please sign up for an account or login below.</h3><br><br>

    <%= button_to 'Sign Up', signup_path, method: "get"%>
    <%= button_to 'Login', login_path, method: "get" %></button>
    <br><br>
    <%= link_to 'Login with GitHub', "/auth/github" %>




  </div>
</div>

app/views/herbs/_form.html.erb
<%= form_for @herb do |f| %>
<% if @herb.errors.any?%>
    <div id="errors_explanation">
      <h3><%= pluralize(@herb.errors.count, "error") %></h3>
      <ul>
      <% @herb.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <strong><%= f.label :name %></strong><br>
    <%= f.text_field :name %><br>
    <br>
    <strong><%= f.label :latin_name, "Latin Name" %></strong><br>
    <%= f.text_field :latin_name %><br>
    <br>
    <strong><%= f.label :family %></strong><br>
    <%= f.text_field :family %><br>
    <br>
    <strong><%= f.label :medicinal_parts, "Medicinal Parts" %></strong><br>
    <%= f.text_field :medicinal_parts %><br>
    <br>
    <strong><%= f.label :taste %></strong><br>
    <%= f.text_field :taste %><br>
    <br>
    <strong><%= f.label :energetics %></strong><br>
    <%= f.text_field :energetics %><br>
    <br>
    <strong><%= f.label :action %></strong><br>
    <%= f.text_field :action %><br>
    <br>
    <strong><%= f.label :ideal_for, "Ideal For Addressing" %></strong><br>
    <%= f.text_area :ideal_for %><br>
    <br>
    <strong><%= f.label :application %></strong><br>
    <%= f.text_area :application %><br>
    <br>
    <strong><%= f.label :dosage %></strong><br>
    <%= f.text_area :dosage %><br>
    <br>
    <strong><%= f.label :considerations %></strong><br>
    <%= f.text_area :considerations %><br>
    <br>
    <%= f.submit "Submit" %>
<% end %>

app/views/herbs/edit.html.erb
<h1>Edit This Herb</h1>

<%= render "form" %>

<%= button_to "Home", home_path, method: "get" %>

app/views/herbs/index.html.erb
<h1>Your Herb List</h1>
<%= form_tag herbs_path, method: "get" do %>
   <%= label_tag(:search, "You may search by name, taste, energetics, action and what the herb is ideal for") %>
   <%= text_field_tag :search, params[:search], placeholder: "Search here" %>
   <%= submit_tag "Search", name: nil%>
<% end %>
<%= flash[:search_error]%>
<%= flash[:empty_results] %>


<ul>
<% @herbs.each do |herb|%>
   <li><p><%= link_to "#{herb.name}", herb_path(herb) %></p></li>
<% end %>
</ul>

<%= button_to "Home", home_path, method: "get" %>
<%= button_to "Create A New Herb", new_herb_path, method: "get" %>

app/views/herbs/new.html.erb
<h1>Create A New Herb</h1>

<%= flash[:herb_not_created] %>

<%= render "form" %>

<%= button_to "Home", home_path, method: "get" %>

app/views/herbs/show.html.erb
<h1><%= @herb.name %></h1>

    <p><strong>Latin Name:</strong> <%= @herb.latin_name %></p>
    <br>
    <p><strong>Family:</strong> <%= @herb.family %></p>
    <br>
    <p><strong>Medicinal Parts:</strong> <%= @herb.medicinal_parts %></p>
    <br>
    <p><strong>Taste:</strong> <%= @herb.taste %></p>
    <br>
    <p><strong>Energetics:</strong> <%= @herb.energetics %></p>
    <br>
    <p><strong>Action:</strong> <%= @herb.action %></p>
    <br>
    <p><strong>Ideal For:</strong> <%= @herb.ideal_for %></p>
    <br>
    <p><strong>Application:</strong> <%= @herb.application %></p>
    <br>
    <p><strong>Dosage:</strong> <%= @herb.dosage %></p>
    <br>
    <p><strong>Considerations:</strong> <%= @herb.considerations %></p><br>
    <br>
    <br>

    <%= button_to "Home", home_path, method: "get" %>
    <%= button_to "Edit This Herb", edit_herb_path, method: 'get' %>
    <%= button_to "Delete This Herb", herb_path, method: 'delete' %>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Your Herb Garden</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head> 
  <body>
  
    <%= yield %>
  <div id="user-widget">
    <% if current_user %>
      Welcome <strong><%= current_user.name %></strong>!
      <%= link_to "Sign out", logout_path, id: "log_out" %>
    <% end %>
   </div>
  </body>
</html>

app/views/remedies/_form.html.erb
<%= form_for [user, remedy] do |f| %>

    <%= f.hidden_field :user_id  %>
    <h4><%= f.label :title, "Remedy Name"%><br></h4>
    <%= f.text_field :title %>
    <br><br>
    <h3>Herbs In Remedy</h3>
    <%= f.fields_for :remedy_herbs, @remedy_herb do |rhf| %>
        <div class="quantity_field">
        <%= rhf.label :quantity %><br>
        <%= rhf.text_field :quantity %>
        </div>
        <div class="herb_field">
        <%= rhf.label :name, "Herb" %><br>
        <%= rhf.collection_select :herb_id, Herb.all, :id, :name%>
        </div>
        <br>
    <% end %>
    <%= f.label :directions %><br>
    <%= f.text_area :directions %><br>
    <br>
    <%= f.submit %>
</div>
<% end %>



    

app/views/remedies/edit.html.erb
<h1>Edit This Remedy</h1>

<div class="alert">
<%= flash[:empty_edit] %>
</div>
<br>

<%= render partial: 'form', locals: {user: @user, remedy: @remedy, remedy_herbs: @remedy_herb}%>
<br>


<%= button_to "Home", home_path, method: "get" %>

app/views/remedies/index.html.erb
<h1>Your Remedies</h1>

<%= form_tag user_remedies_path(current_user), method: "get" do %>
   <%= label_tag(:search, "Search for a Remedy by it's title or by what herbs are in it") %>
   <%= text_field_tag :search, params[:search], placeholder: "Search here" %>
   <%= submit_tag "Search", name: nil%>
<% end %>

<ul>
<% @remedies.each do |remedy|%>
   <li><p><%= link_to "#{remedy.title}", user_remedy_path(current_user, remedy) %></p></li>
<% end %>
</ul>
<br>

<%= button_to "Home", home_path, method: "get" %>
<%= button_to "Create A New Remedy", new_user_remedy_path(current_user), method: "get" %>

app/views/remedies/new.html.erb
<h1>Create A New Remedy</h1>
<div class="alert">
<%= flash[:empty_field] %>
</div>
<br>

<%= render partial: 'form', locals: {user: @user, remedy: @remedy, remedy_herbs: @remedy_herb} %>
<br>

<%= button_to "Home", home_path, method: "get" %>

app/views/remedies/show.html.erb
<h1><%= @remedy.title %><h1>
<ul>
<% @remedy.remedy_herbs.each do |rh| %>
     <li><%= rh.quantity %> - <%= rh.herb.name if rh.herb %></li>
<% end %>
</ul>
<%= @remedy.directions%>

<%= button_to "Home", home_path, method: "get" %>
<%= button_to "Edit This Remedy", edit_user_remedy_path(@remedy), method: "get" %>
<%= button_to "Delete This Remedy", user_remedy_path(@remedy), method: "delete" %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any?%>
    <div id="errors_explanation">
      <h3><%= pluralize(@user.errors.count, "error") %></h3>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email %><br>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %><br>
    <br>
    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %><br>
    <br>
    <%= f.submit "Submit" %>
<% end %>

app/views/users/home.html.erb
<h1>Welcome to Your Medicinal Herb Garden</h1>


<h3>Below you will find links to your list of herbs and your list of remedies</h3>


<h1><%= link_to "Herbs", herbs_path %></h1>
<a href=<%= herbs_url %>><img src="https://storage.needpix.com/rsynced_images/mint-leaves-1397346131HTn.jpg" alt="Close up of Mint leaf" width="400" height="300"></a>

<h1><%= link_to "Remedies", user_remedies_path(current_user) %></h1>
<a href=<%= remedies_url %>><img src="https://cdn.pixabay.com/photo/2020/05/08/10/56/herbs-5145166_1280.jpg" alt="Various herbs in basket next glass container" width="500" height="300"></a>

app/views/users/new.html.erb
<h1>Create A New Account </h1>

 <%= render 'form' %>